language: node_js
node_js: node
branches:
    only:
        - master
        - develop
addons:
    chrome: stable
install:
    - ./scripts/build.sh
script:
    - ./scripts/build.sh
before_deploy:
    - ./scripts/pre-deploy.sh
deploy:
    provider: npm
    email: garrettmanley@gmail.com
    api_key:
        secure: $NPM_TOKEN
    on:
        repo: GarrettManley/ng-blog
        all_branches: true
