language: node_js
node_js: node
branches:
    only:
        - master
        - develop
addons:
    chrome: stable
install:
    - npm install
    - cd ng-blog && npm install && cd ..
script:
    - npm run build
before_deploy:
    - ls -a out
    - npm run patch
deploy:
    provider: npm
    email: garrettmanley@gmail.com
    api_key:
        secure: $NPM_TOKEN
    on:
        repo: GarrettManley/ng-blog
        all_branches: true
